version: '3.8'

services:
  qctwatchdog:
    container_name: "qctwatchdog"
    restart: always
    build:
      context: .
      dockerfile: app/Dockerfile
    command: python run_qctwatchdog.py
    volumes:
      - /home/twkim/P-Drive:/home/twkim/P-Drive
      - qctwatchdog:/data

volumes:
  qctwatchdog:


networks:
  default:
    name: fastapi_default
    external: true
